### ISSUE TITLE
demo里的button替换成textview或imageview就会崩溃~

### ISSUE THREAD

**Issue by ysnows** [AleynP/LPR#11]
2020-06-09 11:41:04.379 25953-25953/com.pcl.lpr E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pcl.lpr, PID: 25953
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getRealMetrics(android.util.DisplayMetrics)' on a null object reference
        at com.pcl.ocr.scanner.ScannerView.getPreviewRatio(ScannerView.java:138)
        at com.pcl.ocr.scanner.ScannerView.initUseCase(ScannerView.java:120)
        at com.pcl.ocr.scanner.ScannerView.lambda$initCamera$0$ScannerView(ScannerView.java:100)
        at com.pcl.ocr.scanner.-$$Lambda$ScannerView$S9Jc7nAK8ybGVA9Y6euMO_ze54w.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ysnows** [comment]
就是MainActivity里的 识别车牌 button
